# Generated by Django 4.1.3 on 2022-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="used_code",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
