# Generated by Django 4.1.3 on 2022-11-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_order_used_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="used_code",
        ),
    ]
