# Generated by Django 4.1.3 on 2022-12-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="https://res.cloudinary.com/dxmms7rbf/image/upload/v1669368875/media/images/avatar_jbs3k2.jpg",
                upload_to="images/",
            ),
        ),
    ]
