# Generated by Django 4.1.3 on 2022-12-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="/static/images/avatar.jpeg", upload_to="images/"
            ),
        ),
    ]
