name: Continuous Integration

on:
  push:
    branches:
      - devops

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: ecommerceapp
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     

      - name: Build and Test
        env:
          DATABASE_NAME: ecommerceapp
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: db
          DATABASE_PORT: 5432
          
        run: |
          docker-compose up -d
          docker-compose exec web sh -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py test"
        
