name: Build and Run Docker Image

on:
  push:
    branches:
      - devops  # Change this to your default branch if it's different

jobs:
  build_and_run_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build Docker image
        run: docker build -t your-docker-image:${{ github.sha }} .

      - name: Set up environment variables
        run: |
          echo "SECRET_KEY=django-insecure-)h20xrma_sa*@s6-)nu9_66evmvb8rr24q99q&f^)j#g%+n&@)" >> $GITHUB_ENV
          echo "DATABASE_NAME=ecommerceapp" >> $GITHUB_ENV
          echo "DATABASE_USER=postgres" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=postgres" >> $GITHUB_ENV
          echo "DATABASE_HOST=db" >> $GITHUB_ENV
          echo "DATABASE_PORT=5432" >> $GITHUB_ENV

      - name: Run Docker image
        run: docker run -d -p 8000:8000 your-docker-image:${{ github.sha }}
