# Generated by Django 4.1.3 on 2022-11-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_productimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
