# Generated by Django 4.1.3 on 2022-11-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"permissions": (("can_edit", "can_delete"),)},
        ),
    ]
