# Generated by Django 4.1.3 on 2022-11-28 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z]*$",
                                "Only alphanumeric characters are allowed.",
                            )
                        ],
                    ),
                ),
                ("value", models.IntegerField(default=50)),
                ("valid_till_date", models.DateField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
