# Generated by Django 4.1.3 on 2022-11-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="is_applied",
            field=models.BooleanField(default=False),
        ),
    ]
